acumatica_subject_area_entities={
	"StockItem": {
		"select_fields": [
			"InventoryID",
			"Description",
			"ItemClass",
			"BaseUOM",
			"DefaultPrice",
			"DefaultWarehouseID",
			"IsAKit",
			"ItemType",
			"ItemStatus",
			"WarehouseDetails/WarehouseID",
			"WarehouseDetails/QtyOnHand",
			"WarehouseDetails/ReplenishmentWarehouse"
		],
		"expand": "WarehouseDetails"
	},
	"ItemWarehouse": {
		"select_fields": [
			"InventoryID",
			"WarehouseID",
			"QtyOnHand",
			"QtyAvailable",
			"ReplenishmentSource"
		],
		"expand": None
	},
	"InventoryReceipt": {
		"select_fields": [
			"ReferenceNbr",
			"Date",
			"Status",
			"TotalQty",
			"TotalCost"
		],
		"expand": None
	},
	"SalesOrder": {
		"select_fields": [
			"OrderType",
			"CustomerID",
			"CustomerOrder",
			"OrderNbr",
			"LocationID",
			"Status",
			"Date",
			"RequestedOn",
			"Description",
			"OrderedQty",
			"OrderTotal",
			"ShipVia",
			"Details/Branch",
			"Details/InventoryID",
			"Details/FreeItem",
			"Details/TaxZone",
			"Details/UOM",
			"Details/WarehouseID",
			"Details/SalespersonID",
			"Details/OrderQty",
			"Details/UnitPrice",
			"Details/ExtendedPrice",
			"Details/DiscountPercent",
			"Details/DiscountAmount",
			"Details/Amount",
			"Details/UnbilledAmount",
			"Details/RequestedOn",
			"Details/ShipOn",
			"Details/Completed",
			"Details/POSource",
			"Details/TaxCategory",
			"Details/LineNbr",
			"Details/UnitCost",
			"Details/LineType",
			"TaxDetails/TaxID",
			"TaxDetails/TaxRate",
			"TaxDetails/TaxableAmount",
			"TaxDetails/TaxAmount",
			"ShipToContact/BusinessName",
			"ShipToContact/Attention",
			"ShipToContact/Phone1",
			"ShipToContact/Email",
			"ShipToAddress/AddressLine1",
			"ShipToAddress/AddressLine2",
			"ShipToAddress/City",
			"ShipToAddress/Country",
			"ShipToAddress/State",
			"ShipToAddress/PostalCode",
			"BillToContact/Attention",
			"BillToContact/Phone1",
			"BillToContact/Email",
			"BillToContact/BusinessName",
			"BillToAddress/AddressLine1",
			"BillToAddress/AddressLine2",
			"BillToAddress/City",
			"BillToAddress/Country",
			"BillToAddress/State",
			"BillToAddress/PostalCode",
			"Shipments/ShipmentType",
			"Shipments/ShipmentNbr",
			"Shipments/Status",
			"Shipments/ShipmentDate",
			"Shipments/ShippedQty",
			"Shipments/ShippedWeight",
			"Shipments/InvoiceNbr",
			"Shipments/InventoryDocType",
			"Shipments/InventoryRefNbr"
		],
		"expand": "Details,TaxDetails,ShipToContact,BillToContact,ShipToAddress,BillToAddress,Shipments,Payments"
	},
	"Shipment": {
		"select_fields": [
			"ShippingSettings/ShipToContact/Attention",
			"ShippingSettings/ShipToContact/BusinessName",
			"ShippingSettings/ShipToContact/Email",
			"ShippingSettings/ShipToContact/Phone1",
			"ShippingSettings/ShipToAddress/AddressLine1",
			"ShippingSettings/ShipToAddress/AddressLine2",
			"ShippingSettings/ShipToAddress/City",
			"ShippingSettings/ShipToAddress/Country",
			"ShippingSettings/ShipToAddress/State",
			"ShippingSettings/ShipToAddress/PostalCode",
			"Details/OrderType",
			"Details/OrderNbr",
			"Details/InventoryID",
			"Details/LocationID",
			"Details/UOM",
			"Details/OrderedQty",
			"Details/ShippedQty",
			"Packages/BoxID",
			"Packages/Confirmed",
			"Packages/Type",
			"Packages/Length",
			"Packages/Width",
			"Packages/Height",
			"Packages/UOM",
			"Packages/Weight",
			"Packages/TrackingNbr",
			"ShipmentNbr",
			"Type",
			"Status",
			"Operation",
			"ShipmentDate",
			"Description",
			"CustomerID",
			"LocationID",
			"WarehouseID",
			"ShippedQty",
			"ShippedWeight",
			"ShippedVolume",
			"PackageWeight",
			"ShipVia"
		],
		"expand": "Details,Packages,ShippingSettings/ShipToContact,ShippingSettings/ShipToAddress"
	},
	"SalesInvoice": {
		"select_fields": [
			"BillingSettings/BillToContact/BusinessName",
			"BillingSettings/BillToContact/Attention",
			"BillingSettings/BillToContact/Email",
			"BillingSettings/BillToContact/Phone1",
			"BillingSettings/BillToAddress/AddressLine1",
			"BillingSettings/BillToAddress/AddressLine2",
			"BillingSettings/BillToAddress/City",
			"BillingSettings/BillToAddress/Country",
			"BillingSettings/BillToAddress/State",
			"BillingSettings/BillToAddress/PostalCode",
			"Commissions/CommissionAmount",
			"Commissions/TotalCommissionableAmount",
			"ReferenceNbr",
			"Status",
			"Date",
			"Type",
			"Description",
			"CustomerID",
			"DetailTotal",
			"TaxTotal",
			"Amount",
			"Balance",
			"Details/Location",
			"Details/BranchID",
			"Details/ShipmentNbr",
			"Details/OrderType",
			"Details/OrderNbr",
			"Details/InventoryID",
			"Details/TransactionDescr",
			"Details/WarehouseID",
			"Details/UOM",
			"Details/Qty",
			"Details/UnitPrice",
			"Details/DiscountAmount",
			"Details/DiscountPercent",
			"Details/Amount",
			"DiscountDetails/DiscountCode",
			"DiscountDetails/SequenceID",
			"DiscountDetails/Type",
			"DiscountDetails/DiscountableAmount",
			"DiscountDetails/DiscountableQty",
			"DiscountDetails/DiscountPercent",
			"DiscountDetails/DiscountAmount"
		],
		"expand": "Details,Commissions,DiscountDetails,BillingSettings/BillToContact,BillingSettings/BillToAddress"
	},
	"Invoice": {
		"select_fields": [
			"ReferenceNbr",
			"LocationID",
			"PostPeriod",
			"Details/ExtendedPrice"
		],
		"expand": "Details"
	}
}

salesforce_subject_area_entities = {
	"Account": {
		"select_fields": [
			"AccountNumber",
			"AccountSource",
			"AnnualRevenue",
			"BillingCity",
			"BillingCountry",
			"BillingCountryCode",
			"BillingPostalCode",
			"BillingState",
			"BillingStateCode",
			"BillingStreet",
			"CreatedById",
			"CreatedDate",
			"Description",
			"Id",
			"Industry",
			"Name",
			"NumberOfEmployees",
			"OperatingHoursId",
			"ParentId",
			"Rating",
			"ShippingCity",
			"ShippingCountry",
			"ShippingCountryCode",
			"ShippingPostalCode",
			"ShippingState",
			"ShippingStateCode",
			"ShippingStreet",
			"Site",
			"Type"
		]
	},
	"Opportunity": {
		"select_fields": [
			"AccountId",
			"Amount",
			"CampaignId",
			"CloseDate",
			"CreatedById",
			"CreatedDate",
			"Description",
			"ExpectedRevenue",
			"ForecastCategoryName",
			"Id",
			"IsWon",
			"LeadSource",
			"Name",
			"NextStep",
			"OwnerId",
			"Pricebook2Id",
			"Probability",
			"StageName",
			"TotalOpportunityQuantity"
		]
	}
}
