"""
Chat Job Service for Simple QnA v2

Manages chat lifecycle via Job Framework.
Chat = Long-running job that persists across multiple queries.
"""
from typing import Optional, Dict, Any, Tuple, List
from datetime import datetime, timezone
from dataclasses import dataclass
from v2.modules.simple_qna.models.simple_qna_models import ChatCreate, ChatResponse
from v2.modules.job_framework.manager.job.job_manager import JobManager
from v2.modules.job_framework.models.job_model import JobCreate, JobUpdate, JobStatus
from v2.modules.simple_qna.constants import MAX_QUERIES_PER_CHAT, AUTO_CLOSE_ON_LIMIT, AUTO_CREATE_NEW_CHAT_ON_ROLLOVER
from v2.common.logger import add_log
from v2.common.gcp import GcpManager
import traceback


@dataclass
class ChatContext:
    """
    Internal context object for chat operations.
    Reduces parameter explosion and improves readability.
    """
    chat_id: str
    user_id: str
    session_id: str
    model: str


class ChatJobService:
    """
    Service for managing chat jobs via Job Framework.
    Each chat is a long-running job that persists across multiple queries.
    """
    
    def __init__(self, job_manager: Optional[JobManager] = None):
        """
        Initialize chat job service.
        
        Args:
            job_manager: Optional JobManager instance (creates new if None)
        """
        self._job_manager = job_manager or JobManager()
        add_log("ChatJobService: Initialized")
    
    async def create_chat_job(self, chat_data: ChatCreate) -> ChatResponse:
        """
        Create a new chat job (long-running job) and deploy Cloud Run service.
        
        The Cloud Run service uses chat_id (job_id), session_id, and user_id to locate
        the input directory for data and domain directory, similar to analysis module.
        
        Args:
            chat_data: Chat creation data
            
        Returns:
            ChatResponse: Created chat response
        """
        try:
            # Create job via Job Framework
            # chat_id will be the job_id (UUID generated by Firestore)
            # Get default model from environment variable
            import os
            default_model = os.getenv("MODEL_NAME", "gpt-5.4")
            
            job_data = JobCreate(
                user_id=chat_data.user_id,
                session_id=chat_data.session_id,
                job_type="simple_qna_chat",
                label=chat_data.label or f"Chat: {chat_data.user_id[:8]}",
                job_config={
                    "model": chat_data.model or default_model,  # Use MODEL_NAME from env if not provided
                    "total_queries": 0,
                    "last_query_at": None,
                    "_original_user_id": chat_data.user_id,
                    "_original_session_id": chat_data.session_id
                }
            )
            
            # Create job WITHOUT execute_func - chat job is just a container
            # If execute_func is provided, Job Framework auto-starts execution
            # Since chat job doesn't need to execute anything, we create it without execute_func
            # This keeps it in PENDING status until first query starts (then transitions to RUNNING)
            job = await self._job_manager._create_job(job_data, execute_func=None)
            chat_id = job.job_id
            
            add_log(f"ChatJobService: Created chat job {chat_id}")
            
            # Deploy Cloud Run service for this chat (like analysis module does)
            # The service uses chat_id, session_id, and user_id to locate input dir and domain directory
            # NOTE: This is synchronous blocking call - chat creation will wait for Cloud Run deployment
            try:
                from v2.modules.session_framework.services.session.session_service import SessionService
                import asyncio
                session_service = SessionService()
                
                add_log(f"ChatJobService: Deploying Cloud Run service for chat {chat_id} (this may take 30-60 seconds)...")
                deploy = await asyncio.to_thread(
                    session_service.deploy_job_service,
                    job_id=chat_id,
                    session_id=chat_data.session_id,
                    user_id=chat_data.user_id
                )
                service_name = deploy.get("service_name")
                service_url = deploy.get("service_url")
                
                if not service_url:
                    raise RuntimeError(f"Cloud Run service deployed but no URL returned for service: {service_name}")
                
                # Construct container URL exactly like analysis module does
                container_url = f"{service_url.rstrip('/')}/simpleqna/analyze_job"
                
                add_log(f"ChatJobService: ✅ Cloud Run service deployed successfully:")
                add_log(f"  - Service Name: {service_name}")
                add_log(f"  - Service URL: {service_url}")
                add_log(f"  - Container URL: {container_url}")
                
                # Store Cloud Run service info in job_config
                # Get current job_config (may have been updated)
                current_job = await self._job_manager._get_job_by_id(chat_id)
                if not current_job:
                    raise RuntimeError(f"Chat job {chat_id} not found after Cloud Run deployment")
                
                job_config = current_job.job_config.copy() if current_job.job_config else {}
                job_config["cloud_run_service_name"] = service_name
                job_config["cloud_run_service_url"] = service_url
                job_config["cloud_run_container_url"] = container_url
                
                await self._job_manager._update_job(
                    chat_id,
                    JobUpdate(job_config=job_config)
                )
                
                # Verify storage by reading back
                verify_job = await self._job_manager._get_job_by_id(chat_id)
                verify_config = verify_job.job_config or {} if verify_job else {}
                stored_url = verify_config.get("cloud_run_container_url")
                
                if stored_url == container_url:
                    add_log(f"ChatJobService: ✅ Verified Cloud Run URL stored correctly for chat {chat_id}")
                else:
                    add_log(f"ChatJobService: ⚠️ WARNING - URL mismatch! Expected: {container_url}, Stored: {stored_url}")
                
                add_log(f"ChatJobService: Cloud Run service deployed and stored for chat {chat_id}: {service_name} -> {container_url}")
            except Exception as deploy_err:
                error_msg = f"Failed to deploy Cloud Run service for chat {chat_id}: {str(deploy_err)} | traceback: {traceback.format_exc()}"
                add_log(f"ChatJobService: {error_msg}")
                # Don't fail chat creation if Cloud Run deployment fails - it can be retried
                # But log the error for debugging
                # Note: Queries will fail if Cloud Run URL is not in job_config
            
            # Job starts as 'pending' - will transition to 'running' when first query starts
            job_status = job.status.value if hasattr(job.status, 'value') else str(job.status)
            
            return ChatResponse(
                chat_id=chat_id,
                user_id=chat_data.user_id,
                session_id=chat_data.session_id,
                status=job_status,
                label=chat_data.label,
                total_queries=0,
                created_on=job.created_on,
                last_query_at=None,
                model=chat_data.model
            )
        except Exception as e:
            add_log(f"ChatJobService: Error creating chat job: {str(e)} | traceback: {traceback.format_exc()}")
            raise
    
    async def check_and_ensure_service_healthy(self, chat_id: str, timeout: int = 5) -> bool:
        """
        Check if Cloud Run service is healthy, and redeploy if not.
        
        Args:
            chat_id: Chat ID (job_id)
            timeout: Timeout in seconds for health check (default: 10)
            
        Returns:
            bool: True if service is healthy (or was successfully redeployed), False otherwise
        """
        try:
            import requests
            
            # Get chat job to extract Cloud Run service URL
            chat_job = await self.get_chat_job(chat_id)
            if not chat_job:
                add_log(f"ChatJobService: Cannot check health - chat {chat_id} not found")
                return False
            
            # Get Cloud Run service URL from job
            job = await self._job_manager._get_job_by_id(chat_id)
            if not job:
                add_log(f"ChatJobService: Cannot check health - job {chat_id} not found")
                return False
            
            job_config = job.job_config or {}
            service_url = job_config.get("cloud_run_service_url")
            
            if not service_url:
                add_log(f"ChatJobService: No Cloud Run service URL found for chat {chat_id} - redeploying...")
                return await self.redeploy_cloud_run_service(chat_id)
            
            # Check health endpoint
            health_url = f"{service_url.rstrip('/')}/health"
            try:
                response = requests.get(health_url, timeout=timeout)
                if response.status_code == 200:
                    health_data = response.json()
                    if health_data.get('status') == 'healthy':
                        add_log(f"ChatJobService: ✅ Cloud Run service is healthy for chat {chat_id}")
                        return True
                    else:
                        add_log(f"ChatJobService: ⚠️ Cloud Run service returned unhealthy status for chat {chat_id}: {health_data}")
                else:
                    add_log(f"ChatJobService: ⚠️ Health check returned {response.status_code} for chat {chat_id}")
            except requests.exceptions.Timeout:
                add_log(f"ChatJobService: ⚠️ Health check timed out for chat {chat_id} - service may be down")
            except requests.exceptions.RequestException as e:
                add_log(f"ChatJobService: ⚠️ Health check failed for chat {chat_id}: {str(e)}")
            
            # Service is unhealthy or unreachable - redeploy
            add_log(f"ChatJobService: Cloud Run service is unhealthy for chat {chat_id} - redeploying...")
            return await self.redeploy_cloud_run_service(chat_id)
            
        except Exception as e:
            add_log(f"ChatJobService: Error checking service health for chat {chat_id}: {str(e)} | traceback: {traceback.format_exc()}")
            return False
    
    async def redeploy_cloud_run_service(self, chat_id: str) -> bool:
        """
        Redeploy Cloud Run service for an existing chat.
        Useful for updating environment variables (e.g., OPENAI_API_KEY) after code changes.
        
        Args:
            chat_id: Chat ID (job_id)
            
        Returns:
            bool: True if redeployment succeeded, False otherwise
        """
        try:
            # Get chat job to extract session_id and user_id
            chat_job = await self.get_chat_job(chat_id)
            if not chat_job:
                add_log(f"ChatJobService: Cannot redeploy - chat {chat_id} not found")
                return False
            
            add_log(f"ChatJobService: Redeploying Cloud Run service for chat {chat_id}...")
            
            # Redeploy Cloud Run service (this will update it with latest env vars)
            from v2.modules.session_framework.services.session.session_service import SessionService
            import asyncio
            session_service = SessionService()
            
            deploy = await asyncio.to_thread(
                session_service.deploy_job_service,
                job_id=chat_id,
                session_id=chat_job.session_id,
                user_id=chat_job.user_id
            )
            service_name = deploy.get("service_name")
            service_url = deploy.get("service_url")
            
            if not service_url:
                add_log(f"ChatJobService: Redeployment failed - no URL returned for service: {service_name}")
                return False
            
            # Construct container URL
            container_url = f"{service_url.rstrip('/')}/simpleqna/analyze_job"
            
            # Update job_config with new URLs
            current_job = await self._job_manager._get_job_by_id(chat_id)
            if not current_job:
                add_log(f"ChatJobService: Cannot update job_config - chat {chat_id} not found")
                return False
            
            job_config = current_job.job_config.copy() if current_job.job_config else {}
            job_config["cloud_run_service_name"] = service_name
            job_config["cloud_run_service_url"] = service_url
            job_config["cloud_run_container_url"] = container_url
            
            await self._job_manager._update_job(
                chat_id,
                JobUpdate(job_config=job_config)
            )
            
            add_log(f"ChatJobService: ✅ Cloud Run service redeployed successfully for chat {chat_id}: {service_name} -> {container_url}")
            return True
        except Exception as e:
            error_msg = f"Failed to redeploy Cloud Run service for chat {chat_id}: {str(e)} | traceback: {traceback.format_exc()}"
            add_log(f"ChatJobService: {error_msg}")
            return False
    
    async def list_chats_by_user_session(self, user_id: str, session_id: str) -> List[ChatResponse]:
        """
        List all chats for a specific user and session.
        
        Args:
            user_id: User ID
            session_id: Session ID
            
        Returns:
            List[ChatResponse]: List of chats for the user/session
        """
        try:
            from v2.common.gcp import GcpManager
            gcp_manager = GcpManager._get_instance()
            firestore_service = gcp_manager._firestore_service
            
            # Query jobs by session_id and job_type, then filter by user_id
            jobs_data = await firestore_service._query_collection(
                "JOBS",
                filters=[
                    ("session_id", "==", session_id),
                    ("job_type", "==", "simple_qna_chat")
                ],
                order_by="created_on",
                order_direction="desc"
            )
            
            chats = []
            for job_doc in jobs_data:
                job_id = job_doc.get('id') or job_doc.get('job_id')
                if not job_id:
                    continue
                
                # Filter by user_id
                doc_user_id = job_doc.get('user_id')
                if doc_user_id != user_id:
                    continue
                
                # Get full job object to build ChatResponse
                job = await self._job_manager._get_job_by_id(str(job_id))
                if not job:
                    continue
                
                chat = await self.get_chat_job(str(job_id))
                if chat:
                    chats.append(chat)
            
            add_log(f"ChatJobService: Found {len(chats)} chats for user {user_id} and session {session_id}")
            return chats
            
        except Exception as e:
            add_log(f"ChatJobService: Error listing chats for user {user_id} and session {session_id}: {str(e)} | traceback: {traceback.format_exc()}")
            return []
    
    async def get_chat_job(self, chat_id: str) -> Optional[ChatResponse]:
        """
        Get chat job by ID.
        
        Args:
            chat_id: Chat ID (job_id)
            
        Returns:
            Optional[ChatResponse]: Chat response if found, None otherwise
        """
        try:
            job = await self._job_manager._get_job_by_id(chat_id)
            if not job:
                return None
            
            # Verify it's a chat job
            if job.job_type != "simple_qna_chat":
                add_log(f"ChatJobService: Job {chat_id} is not a chat job (type: {job.job_type})")
                return None
            
            job_config = job.job_config or {}
            
            return ChatResponse(
                chat_id=job.job_id,
                user_id=job.user_id,
                session_id=job.session_id,
                status=job.status.value if hasattr(job.status, 'value') else str(job.status),
                label=job.label,
                total_queries=job_config.get('total_queries', 0),
                created_on=job.created_on,
                last_query_at=job_config.get('last_query_at'),
                model=job_config.get('model', 'gpt-5.4')
            )
        except Exception as e:
            add_log(f"ChatJobService: Error getting chat job {chat_id}: {str(e)} | traceback: {traceback.format_exc()}")
            return None
    
    async def update_chat_metadata(
        self,
        chat_id: str,
        total_queries: Optional[int] = None,
        last_query_at: Optional[datetime] = None
    ) -> bool:
        """
        Update chat metadata (total_queries, last_query_at).
        
        Terminology:
        - total_queries: Metadata field for UI display (total count of all queries)
        - query_number: Sequential ordering within a chat (1, 2, 3...)
        - completed_query_count: Policy decision field (count of completed queries only)
        
        Args:
            chat_id: Chat ID
            total_queries: New total queries count (metadata only, optional)
            last_query_at: Last query timestamp (optional)
            
        Returns:
            bool: True if updated successfully
        """
        try:
            job = await self._job_manager._get_job_by_id(chat_id)
            if not job:
                return False
            
            job_config = job.job_config or {}
            
            # Update metadata
            if total_queries is not None:
                job_config['total_queries'] = total_queries
            if last_query_at is not None:
                job_config['last_query_at'] = last_query_at.isoformat() if isinstance(last_query_at, datetime) else last_query_at
            
            await self._job_manager._update_job(
                chat_id,
                JobUpdate(job_config=job_config)
            )
            
            add_log(f"ChatJobService: Updated chat metadata for {chat_id}")
            return True
        except Exception as e:
            add_log(f"ChatJobService: Error updating chat metadata for {chat_id}: {str(e)} | traceback: {traceback.format_exc()}")
            return False
    
    async def delete_chat(self, chat_id: str) -> tuple[bool, Optional[str]]:
        """
        Delete a chat and all its data:
        - Cloud Run service
        - All queries in subcollection
        - Job record (and session job_ids update)
        
        Returns:
            tuple: (success: bool, error_message: Optional[str])
        """
        try:
            job = await self._job_manager._get_job_by_id(chat_id)
            if not job:
                return False, f"Chat {chat_id} not found"
            
            if job.job_type != "simple_qna_chat":
                return False, f"Job {chat_id} is not a chat job"
            
            # 1. Delete Cloud Run service
            try:
                job_config = job.job_config or {}
                service_name = job_config.get("cloud_run_service_name")
                if service_name:
                    from v2.modules.session_framework.services.session.session_service import SessionService
                    session_service = SessionService()
                    session_service.delete_job_service(service_name=service_name, job_id=chat_id)
                    add_log(f"ChatJobService: Deleted Cloud Run service {service_name} for chat {chat_id}")
            except Exception as cleanup_err:
                add_log(f"ChatJobService: Warning - Failed to delete Cloud Run service for chat {chat_id}: {str(cleanup_err)}")
            
            # 2. Delete all queries in subcollection
            try:
                from v2.modules.simple_qna.services.query_store_service import QueryStoreService
                query_store = QueryStoreService()
                deleted_count = await query_store.delete_all_chat_queries(chat_id)
                add_log(f"ChatJobService: Deleted {deleted_count} queries for chat {chat_id}")
            except Exception as query_err:
                add_log(f"ChatJobService: Warning - Failed to delete queries for chat {chat_id}: {str(query_err)}")
            
            # 3. Delete job (job record, milestones, session job_ids)
            success = await self._job_manager._delete_job(chat_id)
            if not success:
                return False, f"Failed to delete job record for chat {chat_id}"
            
            add_log(f"ChatJobService: Deleted chat {chat_id}")
            return True, None
        except Exception as e:
            error_msg = f"Error deleting chat {chat_id}: {str(e)} | traceback: {traceback.format_exc()}"
            add_log(f"ChatJobService: {error_msg}")
            return False, error_msg
    
    async def close_chat_job(self, chat_id: str, force: bool = False, _internal_only: bool = False) -> tuple[bool, Optional[str]]:
        """
        Close a chat job (mark as completed).
        After closing, no new queries can be added.
        
        INTERNAL USE ONLY: This method is for system-managed closure (rollover, etc.).
        For manual closure, use Job Framework endpoints directly.
        
        Args:
            chat_id: Chat ID
            force: If True, close even if queries are running (internal use only)
            _internal_only: Flag to indicate this is internal call (prevents accidental external use)
            
        Returns:
            tuple: (success: bool, error_message: Optional[str])
        """
        if not _internal_only:
            add_log(f"ChatJobService: Warning - close_chat_job called without _internal_only flag. This should be internal-only.")
        try:
            job = await self._job_manager._get_job_by_id(chat_id)
            if not job:
                return False, f"Chat {chat_id} not found"
            
            # Verify it's a chat job
            if job.job_type != "simple_qna_chat":
                return False, f"Job {chat_id} is not a chat job"
            
            # Check if there are running queries
            has_running = await self.has_running_queries(chat_id)
            if has_running and not force:
                return False, "Cannot close chat: queries are currently running. Wait for queries to complete or use force=True"
            
            # Update job status to completed
            await self._job_manager._update_job(
                chat_id,
                JobUpdate(
                    status=JobStatus.COMPLETED,
                    completed_at=datetime.now(timezone.utc)
                )
            )
            
            # Clean up Cloud Run service
            try:
                job_config = job.job_config or {}
                service_name = job_config.get("cloud_run_service_name")
                if service_name:
                    from v2.modules.session_framework.services.session.session_service import SessionService
                    session_service = SessionService()
                    session_service.delete_job_service(service_name=service_name, job_id=chat_id)
                    add_log(f"ChatJobService: Cleaned up Cloud Run service {service_name} for chat {chat_id}")
            except Exception as cleanup_err:
                add_log(f"ChatJobService: Warning - Failed to cleanup Cloud Run service for chat {chat_id}: {str(cleanup_err)}")
            
            add_log(f"ChatJobService: Closed chat job {chat_id} (force={force})")
            return True, None
        except Exception as e:
            error_msg = f"Error closing chat job {chat_id}: {str(e)} | traceback: {traceback.format_exc()}"
            add_log(f"ChatJobService: {error_msg}")
            return False, error_msg
    
    async def reopen_completed_chat(self, chat_id: str) -> bool:
        """
        Reopen a completed chat by changing its status back to 'running'.
        This allows adding new queries to old chats.
        
        Args:
            chat_id: Chat ID
            
        Returns:
            bool: True if chat was successfully reopened, False otherwise
        """
        try:
            job = await self._job_manager._get_job_by_id(chat_id)
            if not job:
                add_log(f"ChatJobService: Cannot reopen - chat {chat_id} not found")
                return False
            
            # Verify it's a chat job
            if job.job_type != "simple_qna_chat":
                add_log(f"ChatJobService: Cannot reopen - job {chat_id} is not a chat job (type: {job.job_type})")
                return False
            
            status = job.status.value if hasattr(job.status, 'value') else str(job.status)
            
            # Only reopen if status is 'completed'
            if status == 'completed':
                add_log(f"ChatJobService: Reopening completed chat {chat_id} (status: {status} -> running)")
                await self._job_manager._update_job(
                    chat_id,
                    JobUpdate(status=JobStatus.RUNNING)
                )
                add_log(f"ChatJobService: ✅ Successfully reopened chat {chat_id}")
                return True
            elif status in ['running', 'pending']:
                # Already open, no need to reopen
                return True
            else:
                # Error or cancelled status - cannot reopen
                add_log(f"ChatJobService: Cannot reopen chat {chat_id} with status: {status}")
                return False
        except Exception as e:
            add_log(f"ChatJobService: Error reopening chat {chat_id}: {str(e)} | traceback: {traceback.format_exc()}")
            return False
    
    async def validate_chat_open(self, chat_id: str) -> bool:
        """
        Validate that a chat is open (can accept new queries).
        
        Checks:
        - Chat exists and is a chat job
        - Status is 'pending' or 'running' (not 'completed', 'error', 'cancelled')
        
        Args:
            chat_id: Chat ID
            
        Returns:
            bool: True if chat is open, False otherwise
        """
        try:
            job = await self._job_manager._get_job_by_id(chat_id)
            if not job:
                return False
            
            # Verify it's a chat job
            if job.job_type != "simple_qna_chat":
                return False
            
            # Check status - only pending or running chats can accept queries
            # Reject: completed, error, cancelled
            status = job.status.value if hasattr(job.status, 'value') else str(job.status)
            add_log(f"ChatJobService: Validating chat {chat_id} - current status: {status} (type: {type(job.status).__name__})")
            if status not in ['running', 'pending']:
                add_log(f"ChatJobService: Chat {chat_id} is not open (status: {status}, allowed: ['pending', 'running'])")
                return False
            
            return True
        except Exception as e:
            add_log(f"ChatJobService: Error validating chat {chat_id}: {str(e)} | traceback: {traceback.format_exc()}")
            return False
    
    async def get_or_create_active_chat(
        self,
        user_id: str,
        session_id: str,
        model: str = "gpt-5.4",
        label: Optional[str] = None
    ) -> ChatResponse:
        """
        Get active chat for user/session, or create new one if none exists.
        
        Matches analysis module behavior - lazy chat creation.
        
        Args:
            user_id: User ID
            session_id: Session ID
            model: LLM model to use
            label: Optional chat label
            
        Returns:
            ChatResponse: Active chat (existing or newly created)
        """
        try:
            # Try to find active chat in session
            # Check session's job_ids for active simple_qna_chat jobs
            try:
                gcp_manager = GcpManager._get_instance()
                firestore_service = gcp_manager._firestore_service
                
                # Get session document
                session_doc = await firestore_service._get_document("sessions", session_id)
                if session_doc:
                    job_ids = session_doc.get("jobIds", [])
                    
                    # Check each job to find active chat
                    for job_id in job_ids:
                        job = await self._job_manager._get_job_by_id(str(job_id))
                        if job and job.job_type == "simple_qna_chat":
                            status = job.status.value if hasattr(job.status, 'value') else str(job.status)
                            if status in ['pending', 'running']:
                                # Found active chat
                                chat = await self.get_chat_job(str(job_id))
                                if chat:
                                    add_log(f"ChatJobService: Found active chat {job_id} for session {session_id}")
                                    return chat
            except Exception as e:
                add_log(f"ChatJobService: Error finding active chat: {str(e)}")
            
            # No active chat found - create new one
            add_log(f"ChatJobService: No active chat found - creating new chat for session {session_id}")
            chat_data = ChatCreate(
                user_id=user_id,
                session_id=session_id,
                model=model,
                label=label or f"Chat: {user_id[:8]}"
            )
            return await self.create_chat_job(chat_data)
        except Exception as e:
            add_log(f"ChatJobService: Error in get_or_create_active_chat: {str(e)} | traceback: {traceback.format_exc()}")
            raise
    
    async def get_or_rollover_chat(
        self,
        chat_id: str,
        user_id: str,
        session_id: str,
        model: str = "gpt-5.4",
        label: Optional[str] = None
    ) -> Tuple[str, bool]:
        """
        Get active chat or rollover if limit reached.
        
        Centralized policy enforcement for chat rollover:
        - Checks completed query count
        - Closes chat if limit reached
        - Creates new chat if auto-rollover enabled
        - Returns (chat_id, rolled_over)
        
        This consolidates rollover logic that was previously in execution service.
        
        Args:
            chat_id: Current chat ID
            user_id: User ID
            session_id: Session ID
            model: LLM model
            label: Optional chat label (preserved on rollover)
            
        Returns:
            tuple: (chat_id, rolled_over)
                - chat_id: Active chat ID (may be new if rolled over)
                - rolled_over: True if chat was rolled over, False otherwise
        """
        try:
            # Get current chat to check status and preserve label
            current_chat = await self.get_chat_job(chat_id)
            if not current_chat:
                add_log(f"ChatJobService: Chat {chat_id} not found - cannot rollover")
                return chat_id, False
            
            # Check if rollover is needed
            if not AUTO_CLOSE_ON_LIMIT:
                return chat_id, False
            
            # Get completed query count
            from v2.modules.simple_qna.services.query_store_service import QueryStoreService
            query_store = QueryStoreService()
            completed_query_count = await query_store.get_completed_query_count(chat_id)
            
            if completed_query_count < MAX_QUERIES_PER_CHAT:
                # No rollover needed
                return chat_id, False
            
            # Rollover required
            add_log(f"ChatJobService: Chat {chat_id} reached limit ({completed_query_count}/{MAX_QUERIES_PER_CHAT}) - rolling over")
            
            # Close current chat (internal use)
            success, error_msg = await self.close_chat_job(chat_id, force=False, _internal_only=True)
            if not success:
                add_log(f"ChatJobService: Failed to close chat {chat_id} for rollover: {error_msg}")
                # Continue anyway - validation will catch if chat is not open
            
            # Create new chat if enabled
            if AUTO_CREATE_NEW_CHAT_ON_ROLLOVER:
                # Preserve label from current chat
                new_chat_label = label or current_chat.label or f"Chat: {user_id[:8]}"
                
                new_chat = await self.create_chat_job(
                    ChatCreate(
                        user_id=user_id,
                        session_id=session_id,
                        model=model,
                        label=new_chat_label
                    )
                )
                new_chat_id = new_chat.chat_id
                add_log(f"ChatJobService: Created new chat {new_chat_id} after rollover from {chat_id}")
                return new_chat_id, True
            else:
                add_log(f"ChatJobService: Auto-rollover disabled - cannot create new chat")
                return chat_id, False  # Return original chat_id, but rollover attempted
            
        except Exception as e:
            add_log(f"ChatJobService: Error in get_or_rollover_chat: {str(e)} | traceback: {traceback.format_exc()}")
            # On error, return original chat_id (fail-safe)
            return chat_id, False
    
    async def has_running_queries(self, chat_id: str) -> bool:
        """
        Check if chat has any queries currently running.
        
        Args:
            chat_id: Chat ID
            
        Returns:
            bool: True if any query is running, False otherwise
        """
        try:
            from v2.modules.simple_qna.services.query_store_service import QueryStoreService
            query_store = QueryStoreService()
            queries = await query_store.list_chat_queries(chat_id, order_direction='desc')
            
            # Check if any query is running
            for query in queries:
                if query.status == 'running':
                    return True
            
            return False
        except Exception as e:
            add_log(f"ChatJobService: Error checking running queries for chat {chat_id}: {str(e)} | traceback: {traceback.format_exc()}")
            # On error, assume there might be running queries (fail-safe)
            return True
    
    async def cleanup_inactive_chats(self, inactivity_hours: int = 6) -> int:
        """
        Clean up chat services that have been inactive for specified hours.
        
        Similar to how analysis services are cleaned up after execution completes,
        this method closes chats that haven't received queries for the specified duration
        and deletes their Cloud Run services.
        
        Args:
            inactivity_hours: Hours of inactivity before cleanup (default: 6)
            
        Returns:
            int: Number of chats cleaned up
        """
        try:
            from datetime import datetime, timezone, timedelta
            
            cleaned_count = 0
            cutoff_time = datetime.now(timezone.utc) - timedelta(hours=inactivity_hours)
            
            # Get all chat jobs (simple_qna_chat type)
            # We need to query Firestore for all jobs of type simple_qna_chat
            try:
                from v2.common.gcp import GcpManager
                gcp_manager = GcpManager._get_instance()
                firestore_service = gcp_manager._firestore_service
                
                # Query all jobs with job_type = "simple_qna_chat"
                jobs = await firestore_service._query_collection(
                    "JOBS",
                    filters=[("job_type", "==", "simple_qna_chat")],
                    order_by="created_on",
                    order_direction="desc"
                )
                
                for job_doc in jobs:
                    job_id = job_doc.get('id') or job_doc.get('job_id')
                    if not job_id:
                        continue
                    
                    # Get job via JobManager to ensure we have full job object
                    job = await self._job_manager._get_job_by_id(str(job_id))
                    if not job:
                        continue
                    
                    # Only process pending or running chats (skip already completed/closed)
                    status = job.status.value if hasattr(job.status, 'value') else str(job.status)
                    if status not in ['pending', 'running']:
                        continue
                    
                    # Check last_query_at timestamp
                    job_config = job.job_config or {}
                    last_query_at_str = job_config.get('last_query_at')
                    
                    # If no queries yet, use created_on timestamp
                    if not last_query_at_str:
                        last_query_at = job.created_on
                    else:
                        # Parse ISO format timestamp
                        try:
                            if isinstance(last_query_at_str, str):
                                last_query_at = datetime.fromisoformat(last_query_at_str.replace('Z', '+00:00'))
                            else:
                                last_query_at = last_query_at_str
                        except Exception:
                            # Fallback to created_on if parsing fails
                            last_query_at = job.created_on
                    
                    # Ensure last_query_at is a datetime object with timezone
                    if last_query_at is None:
                        # Skip if no timestamp available
                        continue
                    if isinstance(last_query_at, datetime):
                        # Ensure timezone-aware
                        if last_query_at.tzinfo is None:
                            last_query_at = last_query_at.replace(tzinfo=timezone.utc)
                    else:
                        # Try to convert from timestamp or other format
                        try:
                            if isinstance(last_query_at, (int, float)):
                                last_query_at = datetime.fromtimestamp(last_query_at, tz=timezone.utc)
                            else:
                                # Skip if we can't determine timestamp
                                continue
                        except Exception:
                            continue
                    
                    # Check if inactive
                    if last_query_at < cutoff_time:
                        # Check if there are running queries (don't close if queries are active)
                        has_running = await self.has_running_queries(str(job_id))
                        if has_running:
                            add_log(f"ChatJobService: Skipping cleanup of chat {job_id} - has running queries")
                            continue
                        
                        # Close the chat (this will also clean up Cloud Run service)
                        add_log(f"ChatJobService: Cleaning up inactive chat {job_id} (last query: {last_query_at}, inactive for {inactivity_hours}h)")
                        success, error_msg = await self.close_chat_job(str(job_id), force=False, _internal_only=True)
                        if success:
                            cleaned_count += 1
                            add_log(f"ChatJobService: ✅ Cleaned up inactive chat {job_id}")
                        else:
                            add_log(f"ChatJobService: ⚠️ Failed to cleanup chat {job_id}: {error_msg}")
                
            except Exception as query_err:
                add_log(f"ChatJobService: Error querying jobs for cleanup: {str(query_err)} | traceback: {traceback.format_exc()}")
            
            if cleaned_count > 0:
                add_log(f"ChatJobService: Cleaned up {cleaned_count} inactive chat(s) (inactivity threshold: {inactivity_hours}h)")
            
            return cleaned_count
            
        except Exception as e:
            add_log(f"ChatJobService: Error in cleanup_inactive_chats: {str(e)} | traceback: {traceback.format_exc()}")
            return 0
