"""
Firestore milestone store adapter - Optional plugin
Requires google-cloud-firestore
"""
import asyncio
from typing import Optional, List
from datetime import datetime, timezone
from v2.modules.job_framework.core.interfaces import MilestoneStore
from v2.modules.job_framework.models.job_model import (
    MilestoneCreate, MilestoneResponse, MilestoneUpdate
)
from v2.common.logger import add_log
import traceback


class FirestoreMilestoneStore(MilestoneStore):
    """
    Firestore implementation of MilestoneStore.
    Uses subcollections: JOBS/{job_id}/Milestones
    """
    
    def __init__(
        self,
        firestore_service=None,
        collection_name: str = "JOBS"
    ):
        """
        Initialize Firestore milestone store.
        
        Args:
            firestore_service: Firestore service instance
            collection_name: Jobs collection name (for subcollection path)
        """
        if firestore_service is None:
            try:
                from v2.common.gcp import GcpManager
                gcp_manager = GcpManager._get_instance()
                self._firestore_service = gcp_manager._firestore_service
            except Exception:
                raise ValueError(
                    "FirestoreMilestoneStore requires firestore_service parameter or GcpManager must be configured."
                )
        else:
            self._firestore_service = firestore_service
        
        self._collection_name = collection_name
        add_log("FirestoreMilestoneStore: Initialized with Firestore storage")
    
    async def _create_milestone(self, milestone_data: MilestoneCreate) -> MilestoneResponse:
        """Create a milestone in Firestore subcollection"""
        try:
            milestones_collection = f"{self._collection_name}/{str(milestone_data.job_id)}/Milestones"
            now = datetime.now(timezone.utc)  # Use timezone-aware datetime for Firestore (like jobs)
            
            # Get current job status for milestone (use provided status or fetch from job)
            current_job_status = milestone_data.job_status
            if not current_job_status:
                job_doc = await self._firestore_service._get_document(self._collection_name, milestone_data.job_id)
                current_job_status = job_doc.get('status', 'running') if job_doc else 'running'
            
            milestone_dict = {
                'job_id': milestone_data.job_id,
                'name': milestone_data.name,
                'description': milestone_data.description,
                'job_status': current_job_status,  # Track job status at this milestone point
                'created_at': now,  # Timezone-aware for proper ordering
                'updated_at': now,
                'data': milestone_data.data or {}
            }
            
            # milestone_id is UUID string (generated by Firestore's _create_document)
            milestone_id = await self._firestore_service._create_document(milestones_collection, milestone_dict)
            
            add_log(f"FirestoreMilestoneStore: Created milestone {milestone_id}")
            
            return MilestoneResponse(
                milestone_id=milestone_id,
                job_id=milestone_data.job_id,
                name=milestone_dict['name'],
                description=milestone_dict['description'],
                job_status=milestone_dict['job_status'],
                created_at=milestone_dict['created_at'],
                updated_at=milestone_dict['updated_at'],
                data=milestone_dict['data']
            )
        except Exception as e:
            add_log(f"FirestoreMilestoneStore: Error creating milestone: {str(e)} | traceback: {traceback.format_exc()}")
            raise
    
    async def _get_milestone(self, milestone_id: str, job_id: str) -> Optional[MilestoneResponse]:
        """Get milestone by ID"""
        try:
            milestones_collection = f"{self._collection_name}/{str(job_id)}/Milestones"
            milestone_doc = await self._firestore_service._get_document(milestones_collection, milestone_id)
            
            if not milestone_doc:
                return None
            
            return MilestoneResponse(
                milestone_id=milestone_id,
                job_id=job_id,
                name=milestone_doc['name'],
                description=milestone_doc.get('description'),
                job_status=milestone_doc.get('job_status') or milestone_doc.get('status'),  # Support both for backward compatibility
                created_at=milestone_doc['created_at'],
                updated_at=milestone_doc['updated_at'],
                data=milestone_doc.get('data')
            )
        except Exception as e:
            add_log(f"FirestoreMilestoneStore: Error getting milestone {milestone_id}: {str(e)} | traceback: {traceback.format_exc()}")
            raise
    
    async def _update_milestone(self, milestone_id: str, job_id: str, milestone_data: MilestoneUpdate) -> Optional[MilestoneResponse]:
        """Update a milestone"""
        try:
            milestones_collection = f"{self._collection_name}/{str(job_id)}/Milestones"
            milestone_doc = await self._firestore_service._get_document(milestones_collection, milestone_id)
            
            if not milestone_doc:
                return None
            
            update_data = {}
            if milestone_data.job_status is not None:
                update_data['job_status'] = milestone_data.job_status
            if milestone_data.name is not None:
                update_data['name'] = milestone_data.name
            if milestone_data.description is not None:
                update_data['description'] = milestone_data.description
            if milestone_data.data is not None:
                update_data['data'] = milestone_data.data
            
            update_data['updated_at'] = datetime.now(timezone.utc)  # Use timezone-aware datetime
            
            if update_data:
                await self._firestore_service._update_document(milestones_collection, milestone_id, update_data)
            
            updated_doc = await self._firestore_service._get_document(milestones_collection, milestone_id)
            
            return MilestoneResponse(
                milestone_id=milestone_id,
                job_id=job_id,
                name=updated_doc['name'],
                description=updated_doc.get('description'),
                job_status=updated_doc.get('job_status') or updated_doc.get('status'),  # Support both for backward compatibility
                created_at=updated_doc['created_at'],
                updated_at=updated_doc['updated_at'],
                data=updated_doc.get('data')
            )
        except Exception as e:
            add_log(f"FirestoreMilestoneStore: Error updating milestone {milestone_id}: {str(e)} | traceback: {traceback.format_exc()}")
            raise
    
    async def _get_job_milestones(self, job_id: str) -> List[MilestoneResponse]:
        """Get all milestones for a job, ordered by creation time (created_at)"""
        try:
            milestones_collection = f"{self._collection_name}/{str(job_id)}/Milestones"
            # Use _query_collection with order_by to ensure milestones are returned in creation order
            milestones_data = await self._firestore_service._query_collection(
                milestones_collection,
                order_by='created_at'  # Order by creation time to maintain correct order
            )
            
            milestones = []
            for doc in milestones_data:
                doc_id = doc.get('id', '')
                milestones.append(MilestoneResponse(
                    milestone_id=doc_id,  # milestone_id is UUID string (Firestore document ID)
                    job_id=job_id,
                    name=doc['name'],
                    description=doc.get('description'),
                    job_status=doc.get('job_status') or doc.get('status'),  # Support both for backward compatibility
                    created_at=doc['created_at'],
                    updated_at=doc['updated_at'],
                    data=doc.get('data')
                ))
            add_log(f"FirestoreMilestoneStore: Found {len(milestones)} milestones for job {job_id} (ordered by created_at)")
            return milestones
        except Exception as e:
            add_log(f"FirestoreMilestoneStore: Error getting milestones for job {job_id}: {str(e)} | traceback: {traceback.format_exc()}")
            raise
    
    async def _delete_job_milestones(self, job_id: str) -> None:
        """Delete all milestones for a job"""
        try:
            milestones_collection = f"{self._collection_name}/{str(job_id)}/Milestones"
            milestones = await self._firestore_service._get_all_documents(milestones_collection)
            for milestone in milestones:
                milestone_id = milestone.get('id', '')
                if milestone_id:
                    await self._firestore_service._delete_document(milestones_collection, milestone_id)
        except Exception as e:
            add_log(f"FirestoreMilestoneStore: Error deleting milestones for job {job_id}: {str(e)} | traceback: {traceback.format_exc()}")
